In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
data=pd.read_csv(r"C:\Users\kumar\Downloads\StudentPerformanceFactors.csv")

In [3]:
df=data.copy()

In [171]:
df.head(30)

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,...,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score,Internet_Access_No,Internet_Access_Yes,School_Type_Private,School_Type_Public,Teacher_Quality1
0,23,84,Low,High,No,7,73,Low,Yes,0,...,No,High School,Near,Male,67,0.0,1.0,0.0,1.0,1.0
1,19,64,Low,Medium,No,8,59,Low,Yes,2,...,No,College,Moderate,Female,61,0.0,1.0,0.0,1.0,1.0
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,...,No,Postgraduate,Near,Male,74,0.0,1.0,0.0,1.0,1.0
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,...,No,High School,Moderate,Male,71,0.0,1.0,0.0,1.0,1.0
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,...,No,College,Near,Female,70,0.0,1.0,0.0,1.0,0.0
5,19,88,Medium,Medium,Yes,8,89,Medium,Yes,3,...,No,Postgraduate,Near,Male,71,0.0,1.0,0.0,1.0,1.0
6,29,84,Medium,Low,Yes,7,68,Low,Yes,1,...,No,High School,Moderate,Male,67,0.0,1.0,1.0,0.0,1.0
7,25,78,Low,High,Yes,6,50,Medium,Yes,1,...,No,High School,Far,Male,66,0.0,1.0,0.0,1.0,0.0
8,17,94,Medium,High,No,6,80,High,Yes,0,...,No,College,Near,Male,69,0.0,1.0,1.0,0.0,2.0
9,23,98,Medium,Medium,Yes,8,71,Medium,Yes,0,...,No,High School,Moderate,Male,72,0.0,1.0,0.0,1.0,0.0
10,17,97,Medium,High,Yes,6,87,Low,Yes,2,...,No,High School,Near,Male,71,0.0,1.0,1.0,0.0,0.0
11,21,83,Medium,Medium,Yes,8,97,Low,Yes,2,...,No,High School,Near,Male,70,0.0,1.0,0.0,1.0,1.0
12,9,82,Medium,Medium,Yes,8,72,Medium,Yes,2,...,No,Postgraduate,Near,Male,66,0.0,1.0,1.0,0.0,1.0
13,10,78,Medium,High,Yes,8,74,Medium,Yes,1,...,No,Postgraduate,Near,Male,65,0.0,1.0,1.0,0.0,1.0
14,17,68,Medium,Medium,No,8,70,Medium,Yes,2,...,No,High School,Near,Female,64,0.0,1.0,1.0,0.0,1.0
15,14,60,Medium,Low,Yes,10,65,Low,Yes,0,...,No,College,Near,Male,60,0.0,1.0,1.0,0.0,1.0
16,22,70,Low,Medium,Yes,6,82,Medium,Yes,1,...,No,High School,Near,Female,65,0.0,1.0,0.0,1.0,0.0
17,15,80,Medium,Medium,Yes,9,91,Low,Yes,3,...,No,College,Moderate,Female,67,0.0,1.0,0.0,1.0,1.0
18,12,75,Medium,High,Yes,7,58,Medium,Yes,3,...,No,College,Near,Male,66,0.0,1.0,1.0,0.0,1.0
19,29,78,Medium,Medium,No,5,99,High,Yes,0,...,No,High School,Moderate,Female,69,0.0,1.0,0.0,1.0,1.0
20,19,99,Medium,High,No,6,84,Medium,Yes,1,...,No,High School,Near,Male,72,0.0,1.0,0.0,1.0,0.0
21,20,74,Medium,High,No,8,89,Low,Yes,1,...,No,College,Moderate,Female,66,0.0,1.0,0.0,1.0,1.0
22,11,78,High,Medium,Yes,8,100,High,Yes,1,...,No,High School,Moderate,Male,66,0.0,1.0,0.0,1.0,1.0
23,17,65,Low,High,Yes,5,75,Medium,Yes,2,...,No,High School,Near,Female,63,0.0,1.0,0.0,1.0,1.0
24,21,62,High,Low,Yes,6,54,High,Yes,0,...,No,Postgraduate,Far,Male,64,0.0,1.0,0.0,1.0,0.0
25,13,91,Low,Medium,No,6,90,Medium,Yes,1,...,Yes,High School,Moderate,Female,65,0.0,1.0,0.0,1.0,1.0
26,22,83,High,High,Yes,6,94,Medium,Yes,0,...,No,College,Moderate,Male,71,0.0,1.0,0.0,1.0,1.0
27,16,90,Medium,Medium,No,4,58,Medium,Yes,1,...,No,High School,Moderate,Female,66,0.0,1.0,0.0,1.0,1.0
28,18,66,High,High,No,4,51,Low,Yes,2,...,No,College,Near,Male,64,0.0,1.0,1.0,0.0,1.0
29,16,83,Low,Medium,No,6,57,Medium,Yes,0,...,Yes,High School,Near,Female,63,0.0,1.0,0.0,1.0,2.0

In [5]:
df.dropna(inplace=True)

In [6]:
df.reset_index(inplace=True)

In [7]:
df.drop(columns="index",inplace=True)

In [130]:
#sns.pairplot(data=df)
plt.show()

In [113]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5783 entries, 0 to 5782
Data columns (total 22 columns):
 #   Column                      Non-Null Count  Dtype
---  ------                      --------------  -----
 0   Hours_Studied               5783 non-null   int64
 1   Attendance                  5783 non-null   int64
 2   Parental_Involvement        5783 non-null   object
 3   Access_to_Resources         5783 non-null   object
 4   Extracurricular_Activities  5783 non-null   object
 5   Sleep_Hours                 5783 non-null   int64
 6   Previous_Scores             5783 non-null   int64
 7   Motivation_Level            5783 non-null   object
 8   Internet_Access             5783 non-null   object
 9   Tutoring_Sessions           5783 non-null   int64
 10  Family_Income               5783 non-null   object
 11  Teacher_Quality             5783 non-null   object
 12  School_Type                 5783 non-null   object
 13  Peer_Influence              5783 non-null   object
 14  Physical_Activity           5783 non-null   int64
 15  Learning_Disabilities       5783 non-null   object
 16  Parental_Education_Level    5783 non-null   object
 17  Distance_from_Home          5783 non-null   object
 18  Gender                      5783 non-null   object
 19  Exam_Score                  5783 non-null   int64
 20  Internet_Access_No          5783 non-null   float64
 21  Internet_Access_Yes         5783 non-null   float64
dtypes: float64(2), int64(7), object(13)
memory usage: 994.1+ KB

In [131]:
df["Teacher_Quality"].unique()

array(['Medium', 'High', 'Low'], dtype=object)

In [19]:
df.describe()

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Exam_Score
count,6378.000000,6378.000000,6378.000000,6378.000000,6378.000000,6378.000000,6378.000000
mean,19.977109,80.020853,7.034964,75.066165,1.495296,2.972719,67.252117
std,5.985460,11.550723,1.468033,14.400389,1.233984,1.028926,3.914217
min,1.000000,60.000000,4.000000,50.000000,0.000000,0.000000,55.000000
25%,16.000000,70.000000,6.000000,63.000000,1.000000,2.000000,65.000000
50%,20.000000,80.000000,7.000000,75.000000,1.000000,3.000000,67.000000
75%,24.000000,90.000000,8.000000,88.000000,2.000000,4.000000,69.000000
max,44.000000,100.000000,10.000000,100.000000,8.000000,6.000000,101.000000

In [20]:
q1=df["Exam_Score"].quantile(0.25)
q3=df["Exam_Score"].quantile(0.75)
IQR=q3-q1

In [23]:
min=q1-(IQR*1.5)
max=q3+(IQR*1.5)

In [33]:
df=df[(df["Exam_Score"]<max) & (df["Exam_Score"]>min)]

In [39]:
q1=df["Tutoring_Sessions"].quantile(0.25)
q3=df["Tutoring_Sessions"].quantile(0.75)
IQR=q3-q1
min=q1-(IQR*1.5)
max=q3+(IQR*1.5)

In [41]:
df=df[(df["Tutoring_Sessions"]<max) & (df["Tutoring_Sessions"]>min)]

In [45]:
df.reset_index(inplace=True)

In [132]:
from sklearn.preprocessing import OneHotEncoder,OrdinalEncoder

In [139]:
list=[['High','Medium','Low']]

In [144]:
ord=OrdinalEncoder(categories=list)

In [149]:
df["Teacher_Quality1"]=ord.fit_transform(df[["Teacher_Quality"]])

In [46]:
df.drop(columns="index",inplace=True)

C:\Users\kumar\AppData\Local\Temp\ipykernel_2228\2774306420.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df.drop(columns="index",inplace=True)

In [83]:
one=OneHotEncoder(sparse_output=False)
i=one.fit_transform(df[["Internet_Access"]])

In [115]:
i1=one.fit_transform(df[["School_Type"]])

In [172]:
i2=one.fit_transform(df[["Gender"]])

In [91]:
x=pd.DataFrame(i,columns=one.get_feature_names_out())

In [116]:
x1=pd.DataFrame(i1,columns=one.get_feature_names_out())

In [173]:
x2=pd.DataFrame(i2,columns=one.get_feature_names_out())

In [175]:
df=pd.concat([df,x2],axis=1)

In [97]:
df=pd.concat([df,x],axis=1)

In [118]:
df=pd.concat([df,x1],axis=1)

In [176]:
df.head(4)

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,...,Distance_from_Home,Gender,Exam_Score,Internet_Access_No,Internet_Access_Yes,School_Type_Private,School_Type_Public,Teacher_Quality1,Gender_Female,Gender_Male
0,23,84,Low,High,No,7,73,Low,Yes,0,...,Near,Male,67,0.0,1.0,0.0,1.0,1.0,0.0,1.0
1,19,64,Low,Medium,No,8,59,Low,Yes,2,...,Moderate,Female,61,0.0,1.0,0.0,1.0,1.0,1.0,0.0
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,...,Near,Male,74,0.0,1.0,0.0,1.0,1.0,0.0,1.0
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,...,Moderate,Male,71,0.0,1.0,0.0,1.0,1.0,0.0,1.0

In [151]:
data.shape,df.shape

((6607, 20), (5783, 25))

In [51]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

In [177]:
x=df[["Hours_Studied","Attendance","Sleep_Hours","Previous_Scores","Tutoring_Sessions","Physical_Activity","Internet_Access_No","Internet_Access_Yes","School_Type_Private","School_Type_Public","Gender_Female","Gender_Male"]]
y=df["Exam_Score"]

In [178]:
x_train,x_test,y_train,y_test=train_test_split(x,y,random_state=42,test_size=0.25)

In [179]:
lg=LinearRegression()
lg.fit(x_train,y_train)

LinearRegression()

In [180]:
lg.score(x_test,y_test)

0.8000348516545087

In [181]:
from sklearn.metrics import r2_score,mean_squared_error,mean_absolute_error

In [182]:
np.sqrt(mean_squared_error(y_test,lg.predict(x_test)))

np.float64(1.3901877307052732)

In [183]:
r2_score(y_test,lg.predict(x_test))

0.8000348516545087

In [186]:
lg.predict([[14,84,7,81,0,2,0,1,0,1,1,0]])

c:\Users\kumar\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

array([65.58597546])

In [185]:
x_test.head(10)

,Hours_Studied,Attendance,Sleep_Hours,Previous_Scores,Tutoring_Sessions,Physical_Activity,Internet_Access_No,Internet_Access_Yes,School_Type_Private,School_Type_Public,Gender_Female,Gender_Male
1886,20,90,9,79,2,2,0.0,1.0,0.0,1.0,1.0,0.0
2067,18,95,7,96,2,4,0.0,1.0,1.0,0.0,0.0,1.0
3334,22,80,9,51,2,3,0.0,1.0,0.0,1.0,0.0,1.0
4065,21,74,8,79,0,4,0.0,1.0,1.0,0.0,0.0,1.0
156,31,84,9,87,2,3,0.0,1.0,1.0,0.0,0.0,1.0
4853,13,93,7,51,1,3,0.0,1.0,1.0,0.0,1.0,0.0
4506,19,92,7,90,1,2,0.0,1.0,0.0,1.0,1.0,0.0
2215,17,90,8,65,2,3,0.0,1.0,0.0,1.0,0.0,1.0
5677,8,77,7,90,1,0,0.0,1.0,0.0,1.0,0.0,1.0
2213,14,84,7,81,0,2,0.0,1.0,0.0,1.0,1.0,0.0

In [ ]:
y_test.head(10)

1886    70
2067    70
3334    68
4065    67
156     71
4853    67
4506    70
2215    71
5677    61
2213    66
Name: Exam_Score, dtype: int64

In [188]:
x.columns

Index(['Hours_Studied', 'Attendance', 'Sleep_Hours', 'Previous_Scores',
       'Tutoring_Sessions', 'Physical_Activity', 'Internet_Access_No',
       'Internet_Access_Yes', 'School_Type_Private', 'School_Type_Public',
       'Gender_Female', 'Gender_Male'],
      dtype='object')

In [187]:
from mlxtend.feature_selection import SequentialFeatureSelector

In [245]:
se=SequentialFeatureSelector(lg,k_features=7,forward=True)

In [246]:
se.fit(x,y)

SequentialFeatureSelector(estimator=LinearRegression(), k_features=(7, 7),
                          scoring='r2')

In [247]:
se.k_score_

np.float64(0.8047075471621208)

In [248]:
se.k_feature_names_

('Hours_Studied',
 'Attendance',
 'Previous_Scores',
 'Tutoring_Sessions',
 'Physical_Activity',
 'Internet_Access_No',
 'Internet_Access_Yes')

In [249]:
se.feature_names

['Hours_Studied',
 'Attendance',
 'Sleep_Hours',
 'Previous_Scores',
 'Tutoring_Sessions',
 'Physical_Activity',
 'Internet_Access_No',
 'Internet_Access_Yes',
 'School_Type_Private',
 'School_Type_Public',
 'Gender_Female',
 'Gender_Male']