In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv(r"C:\Users\kumar\Downloads\IMB575-XLS-ENG.csv")

In [14]:
data.head(2)

    Description
0  Other Sauces
1       Cashews

In [6]:
data=df.copy()

In [9]:
data.drop(columns="Member",inplace=True)

In [18]:
data.shape[0]

62141

In [19]:
data.columns

Index(['Description'], dtype='object')

In [22]:
data["Description"][1]

'Cashews'

In [23]:
list=[]
for i in range (0,data.shape[0]):
    for j in data.columns:
        list.append(data["Description"][i])

In [25]:
import collections

In [26]:
p=collections.Counter(list)

In [28]:
sim={"product":p.keys(),"values":p.values()}

In [29]:
sup=pd.DataFrame(sim)

In [33]:
suj=sup.sort_values(by="values",ascending=False)

In [35]:
data["Description"].value_counts()

Description
Other Vegetables             4606
Beans                        4549
Root Vegetables              4303
Other Dals                   3272
Organic F&V                  3113
                             ...
Body Lotion                     1
Talc                            1
Eye Care & Kajal                1
Cookery Books                   1
Dishwash Liquids & Pastes       1
Name: count, Length: 216, dtype: int64

In [34]:
suj.head(10)

             product  values
20  Other Vegetables    4606
27             Beans    4549
19   Root Vegetables    4303
2         Other Dals    3272
32       Organic F&V    3113
25      Whole Spices    3001
47  Gourd & Cucumber    2973
49          Brinjals    2569
3            Namkeen    2224
5             Banana    2188