In [1]:
import pandas as pd

In [7]:
df=pd.read_csv(r"C:\Users\kumar\Downloads\bi.csv",encoding="latin1")

In [14]:
df.describe()

             Age  entryEXAM  studyHOURS     Python          DB
count  77.000000  77.000000   77.000000  75.000000   77.000000
mean   35.207792  76.753247  149.714286  75.853333   69.467532
std    10.341966  16.475784   12.743272  15.410328   17.033701
min    21.000000  28.000000  114.000000  15.000000   30.000000
25%    27.000000  69.000000  144.000000  71.000000   56.000000
50%    33.000000  80.000000  156.000000  81.000000   71.000000
75%    42.000000  90.000000  158.000000  85.000000   83.000000
max    71.000000  98.000000  160.000000  91.000000  100.000000

In [25]:
df.columns=df.columns.str.upper()
df=df.applymap(lambda x:x.upper() if isinstance(x,str) else x)

C:\Users\kumar\AppData\Local\Temp\ipykernel_12160\949631033.py:2: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df=df.applymap(lambda x:x.upper() if isinstance(x,str) else x)

In [26]:
df.head(10)

,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
0,CHRISTINA,BINGER,44,FEMALE,NORWAY,PRIVATE,72,MASTERS,158,59.0,55
1,ALEX,WALEKHWA,60,M,KENYA,PRIVATE,79,DIPLOMA,150,60.0,75
2,PHILIP,LEO,25,MALE,UGANDA,SOGNSVANN,55,HIGHSCHOOL,130,74.0,50
3,SHONI,HLONGWANE,22,F,RSA,SOGNSVANN,40,HIGH SCHOOL,120,NaN,44
4,MARIA,KEDIBONE,23,FEMALE,SOUTH AFRICA,SOGNSVANN,65,HIGH SCHOOL,122,91.0,80
5,HANNAH,HANSEN,25,FEMALE,NORGE,BI RESIDENCE,66,HIGH SCHOOL,130,88.0,59
6,OLE,JOHANSEN,27,MALE,NORWAY,BI-RESIDENCE,90,BACHELORS,156,80.0,91
7,LARS,OLSEN,29,MALE,NORWAY,BIRESIDENCE,89,BARRRCHELORS,160,85.0,60
8,BJØRN,LARSEN,31,MALE,NORWAY,BI RESIDENCE,88,BACHELORS,156,80.0,89
9,SOFIE,JENSEN,33,FEMALE,DENMARK,BI_RESIDENCE,85,BACHELORS,160,83.0,90

In [10]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   fNAME          77 non-null     object
 1   lNAME          77 non-null     object
 2   Age            77 non-null     int64
 3   gender         77 non-null     object
 4   country        77 non-null     object
 5   residence      77 non-null     object
 6   entryEXAM      77 non-null     int64
 7   prevEducation  77 non-null     object
 8   studyHOURS     77 non-null     int64
 9   Python         75 non-null     float64
 10  DB             77 non-null     int64
dtypes: float64(1), int64(4), object(6)
memory usage: 6.7+ KB