In [26]:
import pandas as pd
import numpy as np

In [4]:
df=pd.read_csv(r"C:\Users\kumar\Downloads\archive (3).zip")

In [13]:
df.drop_duplicates(inplace=True)

In [18]:
df.reset_index(inplace=True)

In [14]:
df.duplicated().sum()

np.int64(0)

In [22]:
df.drop(columns=["index","Unnamed: 0"],inplace=True)

In [37]:
df=df.replace("Nan",np.nan)

In [52]:
c=df.columns
d=[]
for i in c:
    d.append(i.upper())
df.columns=d

In [56]:
df["CATEGORY"].unique()

array(['Westernwear-Women', 'Indianwear-Women',
       'Lingerie&Nightwear-Women', 'Footwear-Women', 'Watches-Women',
       'Fragrance-Women', 'Jewellery-Women'], dtype=object)

In [141]:
df["SIZES"]=df["SIZES"].fillna(df["SIZES"].mode()[0])

In [ ]:
df["MRP"].unique()]\

array([ 1699,  3499,  1199, ...,  1080,  1125, 18000], shape=(1097,))

In [82]:
df["MRP"]=df["MRP"].str.replace("Rs\n","")

In [87]:
df["MRP"]=df["MRP"].astype(float)

In [91]:
df["MRP"]=df["MRP"].fillna(round(df["MRP"].mean(),0))

In [90]:
df["MRP"].mean()

np.float64(2638.2167045910855)

In [ ]:
df["SELLPRICE"]=df["SELLPRICE"].astype(float)

In [100]:
df["MRP"]=df["MRP"].astype(int)

In [108]:
df["SELLPRICE"]=df["SELLPRICE"].fillna(round(df["SELLPRICE"].mean(),0))

In [111]:
df["SELLPRICE"]=df["SELLPRICE"].astype(int)

In [113]:
df["DISCOUNT"]=df["DISCOUNT"].str.replace("off","")

In [ ]:
df["DISCOUNT"]=df["DISCOUNT"].str.replace("%","")

In [118]:
df["DISCOUNT"]=df["DISCOUNT"].astype(float)

In [139]:
df["BRANDNAME"]=df["BRANDNAME"].fillna(df["BRANDNAME"].mode()[0])

In [136]:
df["DEATILS"]=df["DEATILS"].fillna(df["DEATILS"].mode()[0])

In [150]:
df["DISCOUNT"]=df["DISCOUNT"].fillna((df["SELLPRICE"]/df["MRP"])*100).tail(40)

In [155]:
df["DISCOUNT"]=round(df["DISCOUNT"],0)

In [157]:
df["DISCOUNT"]=df["DISCOUNT"].astype(str)

In [163]:
df["DISCOUNT"]=df["DISCOUNT"].str.replace(".0","%Off")

In [165]:
df["DISCOUNT"]=df["DISCOUNT"].str.replace("O","o")

In [166]:
df.tail(40)

,BRANDNAME,DEATILS,SIZES,MRP,SELLPRICE,DISCOUNT,CATEGORY
29387,ayesha,womens stone studded drop earrings - multi,"Size:Large,Medium,Small,X-Large,X-Small",698,349,50%off,Jewellery-Women
29388,jewelz,womens stone silver danglers for women,"Size:Large,Medium,Small,X-Large,X-Small",1499,524,65%off,Jewellery-Women
29389,jewelz,ice-cream and new born baby rubber band,"Size:Large,Medium,Small,X-Large,X-Small",909,318,65%off,Jewellery-Women
29390,estelle,womens rhodium plated simple concave hoop earr...,"Size:Large,Medium,Small,X-Large,X-Small",2638,399,15%off,Jewellery-Women
29391,estelle,womens gold plated three daisy flower kundan p...,"Size:Large,Medium,Small,X-Large,X-Small",2638,3299,125%off,Jewellery-Women
29392,michael kors,premium gold womens earrings - mkc1367a1710,"Size:Large,Medium,Small,X-Large,X-Small",6495,2598,60%off,Jewellery-Women
29393,swarovski,constella crystal womens western necklace,"Size:Large,Medium,Small,X-Large,X-Small",2638,10500,398%off,Jewellery-Women
29394,daniel wellington,elan triad ring rose gold - size 60,"Size:Large,Medium,Small,X-Large,X-Small",2638,4199,159%off,Jewellery-Women
29395,estelle,womens gold plated mallika begum kundan earrin...,"Size:Large,Medium,Small,X-Large,X-Small",2638,899,34%off,Jewellery-Women
29396,clara,womens 925 sterling silver freya mangalsutra t...,"Size:Large,Medium,Small,X-Large,X-Small",2399,2279,5%off,Jewellery-Women
29397,estelle,womens gold plated cz mosaic fancy ring (non a...,"Size:Large,Medium,Small,X-Large,X-Small",2638,999,38%off,Jewellery-Women
29398,fossil,vintage gl two tone bracelet - jf02311040,"Size:Large,Medium,Small,X-Large,X-Small",2638,4795,182%off,Jewellery-Women
29399,shaya by caratlane,genda phool bangle in gold plated brass,"Size:Large,Medium,Small,X-Large,X-Small",2638,3200,121%off,Jewellery-Women
29400,estelle,womens gold toned design bracelet,"Size:Large,Medium,Small,X-Large,X-Small",2638,799,30%off,Jewellery-Women
29401,swarovski,crystal stylish womens white earrings,"Size:Large,Medium,Small,X-Large,X-Small",2638,8950,339%off,Jewellery-Women
29402,tribe amrapali,sterling silver gold plated citrine ascending ...,"Size:Large,Medium,Small,X-Large,X-Small",2638,3502,133%off,Jewellery-Women
29403,swarovski,crystal stylish womens blue necklace,"Size:Large,Medium,Small,X-Large,X-Small",2638,7950,301%off,Jewellery-Women
29404,estelle,womens infinity rose gold bracelet using swaro...,"Size:Large,Medium,Small,X-Large,X-Small",2638,799,30%off,Jewellery-Women
29405,jewelz,cotton multicolour girls hair bands,"Size:Large,Medium,Small,X-Large,X-Small",999,349,65%off,Jewellery-Women
29406,ayesha,womens modern shapes with stone statement neck...,"Size:Large,Medium,Small,X-Large,X-Small",698,349,50%off,Jewellery-Women
29407,daniel wellington,elan dual ring rose gold - size 60,"Size:Large,Medium,Small,X-Large,X-Small",2638,4199,159%off,Jewellery-Women
29408,belleziya,combo pack set of 9 gold earrings and set of 3...,"Size:Large,Medium,Small,X-Large,X-Small",2638,1699,64%off,Jewellery-Women
29409,clara,925 silver real pearl aki pendant with chain n...,"Size:Large,Medium,Small,X-Large,X-Small",2199,2089,5%off,Jewellery-Women
29410,ayesha,womens metallic silver double drop with black ...,"Size:Large,Medium,Small,X-Large,X-Small",298,149,50%off,Jewellery-Women
29411,clara,womens 925 sterling silver poppy mangalsutra t...,"Size:Large,Medium,Small,X-Large,X-Small",2699,2564,5%off,Jewellery-Women
29412,fossil,vintage motifs multicolor bracelet - jf02854998,"Size:Large,Medium,Small,X-Large,X-Small",2638,4195,159%off,Jewellery-Women
29413,giva,cubic zirconia silver push back clasp womens e...,"Size:Large,Medium,Small,X-Large,X-Small",1699,1614,5%off,Jewellery-Women
29414,pretty women,womens jad/pearl golden chain - yellow,"Size:Large,Medium,Small,X-Large,X-Small",499,424,15%off,Jewellery-Women
29415,estelle,womens candy bracelet with white american diam...,"Size:Large,Medium,Small,X-Large,X-Small",2638,1299,49%off,Jewellery-Women
29416,jewelz,beautiful white crystal silver plated earrings,"Size:Large,Medium,Small,X-Large,X-Small",1739,608,65%off,Jewellery-Women
29417,ayesha,womens metallic gold statement multilayered ch...,"Size:Large,Medium,Small,X-Large,X-Small",798,399,50%off,Jewellery-Women
29418,jewelz,nine pieces combo fashion non-precious metal b...,"Size:Large,Medium,Small,X-Large,X-Small",1339,468,65%off,Jewellery-Women
29419,pretty women,womens pearl golden drops,"Size:Large,Medium,Small,X-Large,X-Small",449,381,15%off,Jewellery-Women
29420,tribe amrapali,sterling silver oval turquoise ear studs,"Size:Large,Medium,Small,X-Large,X-Small",2638,1030,39%off,Jewellery-Women
29421,swarovski,constella stylish crystal white pierced earrings,"Size:Large,Medium,Small,X-Large,X-Small",2638,8950,339%off,Jewellery-Women
29422,shaya by caratlane,the wing woman clover charm necklace,"Size:Large,Medium,Small,X-Large,X-Small",2638,1250,47%off,Jewellery-Women
29423,swarovski,crystal stylish womens rodhium earrings,"Size:Large,Medium,Small,X-Large,X-Small",2638,8950,339%off,Jewellery-Women
29424,jewelz,ethnic gold plated jhumki earrings,"Size:Large,Medium,Small,X-Large,X-Small",1839,643,65%off,Jewellery-Women
29425,estelle,womens gold plated double line fancy white and...,"Size:Large,Medium,Small,X-Large,X-Small",2638,2799,106%off,Jewellery-Women
29426,estelle,womens gold plated bridge designer mangalsutra...,"Size:Large,Medium,Small,X-Large,X-Small",2638,1899,72%off,Jewellery-Women

In [167]:
df.isna().sum()

BRANDNAME    0
DEATILS      0
SIZES        0
MRP          0
SELLPRICE    0
DISCOUNT     0
CATEGORY     0
dtype: int64

In [57]:
df.describe()

,BRANDNAME,DEATILS,SIZES,MRP,SELLPRICE,DISCOUNT,CATEGORY
count,29420,29420,23226,22413,29420,22413,29427
unique,274,23876,1171,1096,2045,65,7
top,vastranand,synthetic womens casual sandals - black,"Size:Large,Medium,Small,X-Large,X-Small",Rs\n1499,499,50% off,Westernwear-Women
freq,1467,35,1970,925,798,7557,9962

In [58]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 29427 entries, 0 to 29426
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   BRANDNAME  29420 non-null  object
 1   DEATILS    29420 non-null  object
 2   SIZES      23226 non-null  object
 3   MRP        22413 non-null  object
 4   SELLPRICE  29420 non-null  object
 5   DISCOUNT   22413 non-null  object
 6   CATEGORY   29427 non-null  object
dtypes: object(7)
memory usage: 1.6+ MB