import pandas as pd

In [ ]:
import pandas as pd

In [ ]:
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import StandardScaler,MinMaxScaler

In [ ]:
df=pd.read_csv(r"C:\Users\kumar\Downloads\archive (4)\Noisy_Student_Bag_Price_Prediction_Dataset.csv")

In [5]:
df_lable=df.copy()
le=LabelEncoder()
df_lable["Sizee"]=le.fit_transform(df_lable["Size"])
df_lable["Laptop Compartmentt"]=le.fit_transform(df_lable["Laptop Compartment"])
df_lable["Waterprooff"]=le.fit_transform(df_lable["Waterproof"])
print(df_lable[["Size","Laptop Compartment","Waterproof","Sizee","Laptop Compartmentt","Waterprooff"]])

         Size Laptop Compartment Waterproof  Sizee  Laptop Compartmentt  \
0       Small                 No        Yes      2                    0
1       Large                Yes        Yes      0                    1
2       Large                 No        Yes      0                    0
3       Small                Yes         No      2                    1
4       Small                Yes         No      2                    1
...       ...                ...        ...    ...                  ...
52495  Medium                 No        Yes      1                    0
52496   Small                 No        Yes      2                    0
52497   Large                 No        Yes      0                    0
52498   Large                 No         No      0                    0
52499   Large                NaN        Yes      0                    2

       Waterprooff
0                1
1                1
2                1
3                0
4                0
...            ...
52495            1
52496            1
52497            1
52498            0
52499            1

[52500 rows x 6 columns]

In [ ]:
from sklearn.linear_model import LinearRegression
X=[[1],[2],[3],[4],[5]]
y=[40,50,65,75,90]
model=LinearRegression()
model.fit(X,y)
hour=float(input("enter how many hours you have studied:"))
predict=model.predict([[hour]])
print(f"based on your hours {hour} you will get {predict} mark...")

In [1]:
d.head(10)

NameError: name 'd' is not defined

In [11]:
dff=pd.get_dummies(df,columns=['Brand'])
dff

,Material,Size,Compartments,Laptop Compartment,Waterproof,Style,Color,Weight Capacity (kg),Price,Brand_Adidas,Brand_Jansport,Brand_Nike,Brand_Puma,Brand_Under Armour
0,Nylon,Small,2.0,No,Yes,Backpack,Green,13.340058,143.445135,False,True,False,False,False
1,Nylon,Large,4.0,Yes,Yes,Tote,Pink,5.918030,72.086319,False,False,False,False,True
2,Nylon,Large,NaN,No,Yes,Messenger,Red,24.088386,29.699631,False,False,True,False,False
3,Nylon,Small,1.0,Yes,No,Messenger,Pink,5.000000,27.181990,False,False,True,False,False
4,Leather,Small,8.0,Yes,No,NaN,Black,11.258172,71.953236,False,False,False,False,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
52495,Nylon,Medium,3.0,No,Yes,Messenger,Gray,19.774853,61.140497,False,True,False,False,False
52496,NaN,Small,8.0,No,Yes,Messenger,Red,29.822417,47.140186,False,True,False,False,False
52497,Polyester,Large,10.0,No,Yes,Messenger,Red,13.269034,56.184138,False,True,False,False,False
52498,Canvas,Large,5.0,No,No,Messenger,Green,28.132229,112.036966,True,False,False,False,False
52499,Canvas,Large,6.0,No,Yes,Tote,Black,28.414360,42.917005,False,False,True,False,False

In [ ]:
from sklearn.model_selection import train_test_split
d={
    'study':[1,2,3,4,5],
    'test':[40,50,60,70,80]
}
dg=pd.DataFrame(d)
ss=StandardScaler()
sss=ss.fit_transform(dg)
print(pd.DataFrame(sss,columns=['study','test']))

      study      test
0 -1.414214 -1.414214
1 -0.707107 -0.707107
2  0.000000  0.000000
3  0.707107  0.707107
4  1.414214  1.414214

In [ ]:
ms=MinMaxScaler()
mm=ms.fit_transform(dg)
print(pd.DataFrame(mm,columns=['study','test']))

   study  test
0   0.00  0.00
1   0.25  0.25
2   0.50  0.50
3   0.75  0.75
4   1.00  1.00

In [ ]:
X=dg[['study']]
y=dg[['test']]
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)
print(X_train)
print(X_test)

   study
4      5
2      3
0      1
3      4
   study
1      2

In [ ]:
df.head(10)

,Brand,Material,Size,Compartments,Laptop Compartment,Waterproof,Style,Color,Weight Capacity (kg),Price,total
0,Jansport,Nylon,Small,2.0,No,Yes,Backpack,Green,13.3,143.4,156.7
1,Under Armour,Nylon,Large,4.0,Yes,Yes,Tote,Pink,5.9,72.1,78.0
2,Nike,Nylon,Large,4.0,No,Yes,Messenger,Red,24.1,29.7,53.8
3,Nike,Nylon,Small,1.0,Yes,No,Messenger,Pink,5.0,27.2,32.2
4,Under Armour,Leather,Small,8.0,Yes,No,Tote,Black,11.3,72.0,83.3
5,Puma,Canvas,Medium,8.0,No,No,Messenger,Pink,17.0,116.3,133.3
6,Jansport,Polyester,Large,5.0,Yes,No,Tote,Black,20.2,44.5,64.7
7,Nike,Leather,Medium,8.0,No,Yes,Backpack,NaN,6.4,55.0,61.4
8,Adidas,Nylon,Large,3.0,Yes,No,Tote,Pink,24.0,118.9,142.9
9,Adidas,Canvas,Small,8.0,Yes,No,Messenger,Pink,30.0,124.8,154.8