In [1]:
import pandas as pd

In [2]:
df=pd.read_csv(r"C:\Users\kumar\Downloads\bi.csv",encoding="latin1")

In [6]:
c=df.columns
d=[]
for i in c:
    d.append(i.upper())
df.columns=d

In [8]:
df.describe()

             AGE  ENTRYEXAM  STUDYHOURS     PYTHON          DB
count  77.000000  77.000000   77.000000  75.000000   77.000000
mean   35.207792  76.753247  149.714286  75.853333   69.467532
std    10.341966  16.475784   12.743272  15.410328   17.033701
min    21.000000  28.000000  114.000000  15.000000   30.000000
25%    27.000000  69.000000  144.000000  71.000000   56.000000
50%    33.000000  80.000000  156.000000  81.000000   71.000000
75%    42.000000  90.000000  158.000000  85.000000   83.000000
max    71.000000  98.000000  160.000000  91.000000  100.000000

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 77 entries, 0 to 76
Data columns (total 11 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   FNAME          77 non-null     object
 1   LNAME          77 non-null     object
 2   AGE            77 non-null     int64
 3   GENDER         77 non-null     object
 4   COUNTRY        77 non-null     object
 5   RESIDENCE      77 non-null     object
 6   ENTRYEXAM      77 non-null     int64
 7   PREVEDUCATION  77 non-null     object
 8   STUDYHOURS     77 non-null     int64
 9   PYTHON         75 non-null     float64
 10  DB             77 non-null     int64
dtypes: float64(1), int64(4), object(6)
memory usage: 6.7+ KB

In [10]:
df["GENDER"].unique()

array(['Female', 'M', 'Male', 'F', 'female', 'male'], dtype=object)

In [11]:
df["GENDER"]=df["GENDER"].apply(lambda x:"M" if "Male" else "F")

In [13]:
df["GENDER"].unique()

array(['M'], dtype=object)

In [12]:
df.head(10)

,FNAME,LNAME,AGE,GENDER,COUNTRY,RESIDENCE,ENTRYEXAM,PREVEDUCATION,STUDYHOURS,PYTHON,DB
0,Christina,Binger,44,M,Norway,Private,72,Masters,158,59.0,55
1,Alex,Walekhwa,60,M,Kenya,Private,79,Diploma,150,60.0,75
2,Philip,Leo,25,M,Uganda,Sognsvann,55,HighSchool,130,74.0,50
3,Shoni,Hlongwane,22,M,Rsa,Sognsvann,40,High School,120,NaN,44
4,Maria,Kedibone,23,M,South Africa,Sognsvann,65,High School,122,91.0,80
5,Hannah,Hansen,25,M,Norge,BI Residence,66,High School,130,88.0,59
6,Ole,Johansen,27,M,Norway,BI-Residence,90,Bachelors,156,80.0,91
7,Lars,Olsen,29,M,norway,BIResidence,89,Barrrchelors,160,85.0,60
8,Bjørn,Larsen,31,M,Norway,BI Residence,88,Bachelors,156,80.0,89
9,Sofie,Jensen,33,M,Denmark,BI_Residence,85,Bachelors,160,83.0,90